# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Strassenachsen
                                 A QGIS plugin
 Anlegen und Prüfen der Straßenachsen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-22
        copyright            : (C) 2022 by Katharina Fritzler
        email                : Katharina.Fritzler@stud.hs-Bochum.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Strassenachsen class from file Strassenachsen.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Strassenachsen import Strassenachsen
    return Strassenachsen(iface)
